### ISSUE TITLE
Custom cool Help commands shit

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#22] opened 2021-10-30 14:51 UTC
Help : arrow keys and menus
Custom help commands - https://www.youtube.com/watch?v=xsA5QAkr-04&list=PL9YUC9AZJGFG6larkQJYio_f0V-O1NRjy&index=7

**Comment by kevslinger** [comment] 2021-11-03 23:09
Duplicate of #15

**Closed by kevslinger** 2021-11-03 23:09 UTC
